```java
// Java program to add two positive numbers

public class Main {
    // Method to add two positive integers
    public static int addPositiveNumbers(int num1, int num2) {
        // Check if numbers are positive
        if(num1<0 || num2<0) {
            throw new IllegalArgumentException("Only positive numbers are allowed");
        }
        
        // Return the sum of the two numbers
        return num1 + num2;
    }

    public static void main(String[] args) {
        // Test the addPositiveNumbers method
        int num1 = 5;
        int num2 = 10;
        
        // Print the result of the addition
        System.out.println("The sum of " + num1 + " and " + num2 + " is " + addPositiveNumbers(num1, num2));
    }
}
```
// generated by TicketToPR at 2026-08-14 17:25:57
