```python
#Function to implement Bellman Ford Algorithm
def BellmanFord(graph, V, E, src):
    # Initializing distance array from source vertex to all vertices as INFINITE and distance of source vertex as 0. 
    dis = [float("Inf")] * V
    dis[src] = 0

    # Relax all edges |V| - 1 times to get shortest possible distance
    for i in range(V - 1):
        for j in range(E):
            if dis[graph[j][0]] + graph[j][2] < dis[graph[j][1]]:
                dis[graph[j][1]] = dis[graph[j][0]] + graph[j][2]

    # Check for negative-weight cycles.  
    # If we get a shorter path, then there is a cycle. 
    for i in range(E):
        x = graph[i][0]
        y = graph[i][1]
        weight = graph[i][2]
        if dis[x] != float("Inf") and dis[x] + weight < dis[y]:
            print("Graph contains negative weight cycle")
            return
 
    # Print all distance
    print("Vertex Distance from Source")
    for i in range(V):
        print(("{} \t\t {}".format(i, dis[i])))
```
# generated by TicketToPR at 2025-09-26 00:45:41
