```python
def bellman_ford(graph, source_node):
    # Total number of nodes in the graph
    total_nodes = len(graph)
    
    # Initialize shortest distance for all nodes as infinite and source node as zero
    shortest_distance = [float('inf')] * total_nodes
    shortest_distance[source_node] = 0

    # Relax edges total_nodes - 1 times
    for _ in range(total_nodes - 1):
        for node, edges in enumerate(graph):
            for neighbour, weight in edges:
                if shortest_distance[node] != float('inf'):
                    new_distance = shortest_distance[node] + weight
                    if new_distance < shortest_distance[neighbour]:
                        shortest_distance[neighbour] = new_distance

    # Check for negative-weight cycles
    for node, edges in enumerate(graph):
        for neighbour, weight in edges:
            if shortest_distance[node] != float('inf'):
                if shortest_distance[node] + weight < shortest_distance[neighbour]:
                    raise Exception("Graph contains a negative-weight cycle")
                    
    # Return the shortest distance list
    return shortest_distance
```
# generated by TicketToPR at 2025-09-26 00:47:03
