```java
import java.util.*; 

// Node class representing a node in the graph
class Node implements Comparable<Node> {
    public Integer id;
    public Integer distance;

    public Node(Integer id, Integer distance) {
        this.id = id;
        this.distance = distance;
    }
    
    @Override
    public int compareTo(Node other) {
        return this.distance.compareTo(other.distance);
    }
}

public class Dijkstra {
    
    // Function that implements Dijkstra's algorithm
    public void dijkstra(List<List<Node>> adj, int src, int N) {
        // Priority queue to check for shortest distance
        PriorityQueue<Node> pq = new PriorityQueue<>();
        // Distance list
        List<Integer> dist = new ArrayList<>(Collections.nCopies(N, Integer.MAX_VALUE));
        
        // Add source node to the priority queue
        pq.add(new Node(src, 0));
        
        // Distance to the source is 0
        dist.set(src, 0);
        
        while (!pq.isEmpty()) {
            // node with the least distance will be removed from the priority queue
            Integer u = pq.poll().id;
        
            // go through all the adjacent nodes
            for (Node node : adj.get(u)) {
                Integer v = node.id;
                Integer weight = node.distance;

                // If current node distance + edge weight is less than the destination node weight,
                // then update the distance
                if (dist.get(u) + weight < dist.get(v)) {
                    dist.set(v, dist.get(u) + weight);
                    pq.add(new Node(v, dist.get(v)));
                }
            }
        }
        
        // Print the shortest distance from the source to all other nodes
        for (int i = 0; i < N; ++i)
            System.out.println("Distance from "+ src +" to "+ i +" is "+ dist.get(i));
    }
}
```
// generated by TicketToPR at 2025-09-24 19:59:17
