```python
import heapq

def dijkstra(graph, start_vertex):
    # Initialize dictionaries to store distance and predecessors
    distance = {vertex: float('infinity') for vertex in graph}
    distance[start_vertex] = 0
    # Initialize an empty dictionary to store the path
    path = {}

    # Initialize a priority queue for vertices
    queue = [(0, start_vertex)]

    while queue:
        # Pop a vertex from the queue
        current_distance, current_vertex = heapq.heappop(queue)

        # Ignore if the popped vertex's distance got updated
        if current_distance > distance[current_vertex]:
            continue

        # For each neighbour of the vertex, update the distance 
        for neighbour, weight in graph[current_vertex].items():
            new_distance = current_distance + weight

            # If the new calculated distance for neighbour is less than the old one,
            # update it in the distance dictionary and push the neighbour in queue
            if new_distance < distance[neighbour]:
                distance[neighbour] = new_distance
                path[neighbour] = current_vertex
                heapq.heappush(queue, (new_distance, neighbour))

    # Return the distance dictionary and the path dictionary
    return distance, path
```

# generated by TicketToPR at 2025-09-24 19:58:04
