```python
# initialize the variables c and d with the numbers to be divided
c = 10
d = 2

# Use try/except block to catch and handle exceptions 
try:
    # Check if d is zero to prevent ZeroDivisionError
    if d == 0:
        print("Error: Division by zero is undefined")
    else:
        # perform division operation
        res = c / d
except Exception as e:  # catch exceptions
    print("Error: ", e)
else:
    # print the result of the division
    print("Result: ", res)
```
# generated by TicketToPR at 2025-09-12 18:57:48
