```python
def divide_two_numbers(c, d):
    # Guard clause for division by zero
    if d == 0:
        raise ValueError("Cannot divide by zero")

    # Perform division
    result = c / d

    # Return result
    return result
```
# generated by TicketToPR at 2025-09-12 18:56:54
