```java
public class MatrixAddition {
  
    // Method to add two matrices
    public static int[][] addTwoMatrices(int[][] A, int[][] B) {
        // Initialize row and column length
        int rows = A.length;
        int cols = A[0].length;
        
        // Resultant matrix to store the sum
        int[][] result = new int[rows][cols]; 

        // Iterating through each element in matrices
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < cols; j++) {
                // Add corresponding elements of two matrices
                result[i][j] = A[i][j] + B[i][j];
            }
        }
        
        // Return the resultant matrix
        return result;
    }
}
```
// generated by TicketToPR at 2026-08-14 15:39:45
