```java
// Class to handle matrix operations
public class MatrixOperations {

    // Method to add two matrices
    public static int[][] addMatrices(int[][] matrix1, int[][] matrix2) {
        // Get the dimensions of the matrices
        int rows = matrix1.length;
        int columns = matrix1[0].length;

        // Initialize the result matrix
        int[][] resultMatrix = new int[rows][columns];

        // Loop over each element in the matrices
        for (int i = 0; i < rows; i++) {
            for (int j = 0; j < columns; j++) {
                // Add the corresponding elements of the two matrices
                resultMatrix[i][j] = matrix1[i][j] + matrix2[i][j];
            }
        }

        // Return the resulting matrix
        return resultMatrix;
    }
}
```
// generated by TicketToPR at 2026-08-14 15:38:36
