```Java
public class MultiplyTwoNewMatrices {
    /*
     * This method multiplies two matrices and returns the result.
     */
    public static int[][] multiplyMatrices(int[][] firstMatrix, int[][] secondMatrix) {
        int r1 = firstMatrix.length;
        int c1 = firstMatrix[0].length;
        int c2 = secondMatrix[0].length;
        int[][] product = new int[r1][c2];

        // Multiplying and storing in product
        for (int i = 0; i < r1; i++) {
            for (int j = 0; j < c2; j++) {
                for (int k = 0; k < c1; k++) {
                    product[i][j] += firstMatrix[i][k] * secondMatrix[k][j];
                }
            }
        }
        return product;
    }
}
```
// generated by TicketToPR at 2026-08-14 15:37:30
