```java
public class MatrixMultiplication {
    
    // Function to multiply two matrices
    public static int[][] multiplyMatrices(int[][] firstMatrix, int[][] secondMatrix, int r1, int c1, int c2) {
        int[][] result = new int[r1][c2];
        
        for (int i = 0; i < r1; i++) { 
            for (int j = 0; j < c2; j++) { 
                result[i][j] = 0; 
                for (int k = 0; k < c1; k++) {
                    // Multiply the corresponding elements from first and second matrices and add them
                    result[i][j] += firstMatrix[i][k] * secondMatrix[k][j]; 
                }
            } 
        } 
        
        return result;
    } 

    public static void main(String[] args) {
        int r1 = 2, c1 = 3;
        int r2 = 3, c2 = 2;

        // First matrix
        int[][] firstMatrix = { {3, -2, 5}, {3, 0, 4} };

        // Second matrix
        int[][] secondMatrix = { {2, 3}, {-9, 0}, {0, 4} };

        // Check if matrices can be multiplied
        if (c1 != r2) {
            System.out.println("The matrices can't be multiplied");
        } else {
            // Call the multiply function
            int[][] result = multiplyMatrices(firstMatrix, secondMatrix, r1, c1, c2);
            
            // Print result
            System.out.println("Multiplication of two matrices: ");
            for (int[] row : result) {
                for (int column : row) {
                    System.out.print(column + "    ");
                }
                System.out.println();
            }
        }
    }
}
```
// generated by TicketToPR at 2026-08-14 15:32:55
