```java
public class MultiplyTwoMatrices {

    public int[][] multiplyMatrix(int[][] matrix1, int[][] matrix2) {
        
        // Calculate the size of the matrices 
        int r1 = matrix1.length;
        int c1 = matrix1[0].length;
        int r2 = matrix2.length;
        int c2 = matrix2[0].length;
        
        // The two matrices can be multiplied only when number of columns in first matrix is equal to number of rows in second matrix
        if(c1 != r2) { 
            System.out.println("The matrices can't be multiplied...");
            return null;
        }

        // Create product matrix to store the result
        int[][] product = new int[r1][c2];

        // Perform matrix multiplication
        for(int i = 0; i < r1; i++) {
            for(int j = 0; j < c2; j++) {
                for(int k = 0; k < c1; k++) {
                    product[i][j] += matrix1[i][k] * matrix2[k][j];
                }
            }
        }

        return product;
    }
}
```
// generated by TicketToPR at 2026-08-14 15:34:16
