```python
# Function to subtract two numbers
def subtract_numbers(num1, num2):
    # Subtract num2 from num1
    result = num1 - num2
    
    # Return the result
    return result
```
# generated by TicketToPR at 2025-09-12 18:19:44
