```python
def subtract_numbers(a, b):
    """
    Subtracts the second number from the first number.

    Parameters:
        a (int or float): The first number.
        b (int or float): The second number to be subtracted from the first.

    Returns:
        result (int or float): The result of subtracting the second number from the first.
    """
    result = a - b
    return result
```
# generated by TicketToPR at 2025-09-12 18:20:24
