```python
# Function to subtract two numbers
def subtract_numbers(c, d):
    """Take two numbers as inputs and return their difference."""
    
    # Calculate the difference
    difference = c - d
    
    return difference
```
# generated by TicketToPR at 2025-09-12 18:20:51
