```java
public class Main {

    // Method to add three numbers
    public static int addThreeNumbers(int num1, int num2, int num3) {
        // The arithmetic expression num1 + num2 + num3 adds the numbers together
        int sum = num1 + num2 + num3;

        // The function then returns this sum to the caller
        return sum;
    }

    public static void main(String[] args) {
        // Example usage: add numbers 10, 20, and 30
        int result = addThreeNumbers(10, 20, 30);

        // Output the result
        System.out.println("The sum is: " + result);
    }
}
```
// generated by TicketToPR at 2025-11-10 21:48:15
