```typescript
/**
 * This function receives two numbers as parameters
 * and return their sum.
 *
 * @param num1 - The first number
 * @param num2 - The second number
 * @returns The sum of num1 and num2
 */
function addTwoNumbers(num1: number, num2: number): number {
    return num1 + num2;
}
```
// generated by TicketToPR at 2025-09-11 16:20:34
