```python
import json

def is_valid_json(s):
    """Check if a string is valid JSON.
    
    Args:
        s (str): The string to check.

    Returns:
        bool: True if the string is valid JSON, False otherwise.
    """
    try:
        json.loads(s)
        return True
    except ValueError:
        return False
```
# generated by TicketToPR at 2025-09-11 15:48:22
