```python
import json

# Function to validate JSON data
def validate_json(data):
    try:
        # Try to load the data as JSON
        json.loads(data)
        return True
    except ValueError as e:
        # If a ValueError is raised, the data is not valid JSON
        print("Invalid JSON: %s" % str(e))
        return False

# Some examples of JSON data to validate
valid_json = '{"name": "John", "age": 30, "city": "New York"}'
invalid_json = '{name: "John", age: 30, city: "New York"}'

print(validate_json(valid_json))  # True
print(validate_json(invalid_json))  # False

# More complex example
nested_json = '{"employees":[{"firstName":"John", "lastName":"Doe"}, {"firstName":"Anna", "lastName":"Smith"}, {"firstName":"Peter", "lastName":"Jones"}]}'
print(validate_json(nested_json))  # True

# Example with syntax error
invalid_syntax_json = '{"employees":[{"firstName":"John", "lastName":"Doe"}, {"firstName":"Anna", "lastName":"Smith", "firstName":"Peter", "lastName":"Jones"}]}'
print(validate_json(invalid_syntax_json))  # False
```
# generated by TicketToPR at 2025-09-11 15:58:15
