```python
import json

def validate_json(json_data):
    """
    Verifies if a text is a valid JSON.

    :param json_data: A text to be verified
    :return: JSON validation result and error message if any
    """
    try:
        json.loads(json_data)  # Try to load the JSON data
        return True, None  # If successful, return True and None for error
    except ValueError as e:  # Catch the ValueError exception if json.loads() fails
        return False, str(e)  # Return False and the error message
        

# Example usage:
json_data_correct = '{"name": "John", "age": 31, "city": "New York"}'
json_data_incorrect = '{"name": "John", "age: 31, "city": "New York"}'  # Missing quote

is_valid, error = validate_json(json_data_correct)
if is_valid:
    print("The first JSON is valid")
else:
    print(f"Invalid JSON. Error: {error}")

is_valid, error = validate_json(json_data_incorrect)
if is_valid:
    print("The second JSON is valid")
else:
    print(f"Invalid JSON. Error: {error}")
```

# generated by TicketToPR at 2025-09-11 15:50:04
